pipelines:
  default:
    - step:
        image: circleci/golang:1.10
        script:
          - export WEAVEWORKS_GO_HOME=/go/src/github.com/weaveworks
          - mkdir -p $WEAVEWORKS_GO_HOME
          - ln -s $BITBUCKET_CLONE_DIR $WEAVEWORKS_GO_HOME/flux
          - cd $WEAVEWORKS_GO_HOME/flux
          - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          - dep ensure -vendor-only
          - make check-generated
          - make test TEST_FLAGS="-race -tags integration -timeout 60s"
          - make all
          - echo ${GCR_JSON_KEY_1ST_DEV} | docker login -u _json_key --password-stdin https://us.gcr.io
          - |
            docker push
            us.gcr.io/first-gaming-dev/flux-helm-operator
            us.gcr.io/first-gaming-dev/flux-helm-operator:$(docker/image-tag)
            us.gcr.io/first-gaming-dev/flux-flux
            us.gcr.io/first-gaming-dev/flux-flux:$(docker/image-tag)
        services:
          - docker
          - memcache
        caches:
          - docker
          - dep
definitions:
  services:
    memcache:
      image: memcached
  caches:
    dep: /go/pkg/dep
