#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v gometalinter) ]
then
	go get github.com/alecthomas/gometalinter
	gometalinter --update --install
fi

gometalinter \
	--vendor \
    --exclude='error return value not checked.*(Close|Log|Print|Encode).*\(errcheck\)$' \
    --exclude='.*_test\.go:.*error return value not checked.*\(errcheck\)$' \
    --disable-all \
    --enable=vet \
    --enable=gocyclo \
    --enable=gofmt \
	--deadline=60s \
	./...

# Disabled golint and lll, because there's far too many errors!
# Also disabled --enable=errcheck for now